### ISSUE TITLE
Settings in Docker

### ISSUE THREAD

**Issue by camjac251** [uhthomas/kipp#11]
Is it possible to add an option to control the options with Docker? I think since the refactor, some stuff has been stripped from the earlier version, including much of the readme.

Would it be possible to change the variables here https://github.com/uhthomas/kipp/blob/master/cmd/kipp/serve.go but inside of the Docker image? I couldn't find a way to change the endpoint through docker run successfully.

**Comment by uhthomas** [comment]
Running shouldn't be any different in Docker than as a raw binary. Depending on what you want to do, you should be able to do
```
$ docker run uhthomas/kipp:latest -addr :1234
2020/05/12 14:52:20 listening on :1234
```

There's a few things that need to be worked on (specifically, changing the database and filesystem via flags, and automatic deletion of files), but everything else should be the same.

When you say change the endpoint, I assume you mean the endpoint of which files are uploaded to? So instead of making a request `POST /`, you would want `POST /some-endpoint`? In that instance, it's better to proxy it behind something like nginx and let it do all the heavy lifting 😄

Let me know if I can help out.

**Comment by camjac251** [comment]
Ah I just meant the docker endpoint is what I tried to change because I didn't think to try adding variables like your example. I just assumed they wouldn't work

**Comment by uhthomas** [comment]
I'm going to close this for now as I think your question was answered 😄 feel free to re-open if you think it's necessary.
